workflows:
  Workflow:
    name: Workflow
    instance_type: mac_mini
    environment:
    cache:
      cache_paths:
        - ~/.pub-cache
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ./gradle assembleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.apk
      scripts:
        - echo 'Post-publish script'
